//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Serveurs.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spotifyceri.Demo;

/** @hidden */
public class _NLPPrxI extends com.zeroc.Ice._ObjectPrxI implements NLPPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
