//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Serveurs.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spotifyceri.Demo;

/**
 * Helper class for marshaling/unmarshaling SongList.
 **/
public final class SongListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Song[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Song.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Song[] read(com.zeroc.Ice.InputStream istr)
    {
        final Song[] v;
        final int len0 = istr.readAndCheckSeqSize(12);
        v = new Song[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Song.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Song[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Song[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            SongListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<Song[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            Song[] v;
            v = SongListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
