//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Serveurs.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.spotifyceri.Demo;

public interface VLCPrx extends com.zeroc.Ice.ObjectPrx
{
    default void sayHelloVLC()
    {
        sayHelloVLC(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sayHelloVLC(java.util.Map<String, String> context)
    {
        _iceI_sayHelloVLCAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sayHelloVLCAsync()
    {
        return _iceI_sayHelloVLCAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sayHelloVLCAsync(java.util.Map<String, String> context)
    {
        return _iceI_sayHelloVLCAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sayHelloVLCAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sayHelloVLC", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void playStream()
    {
        playStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void playStream(java.util.Map<String, String> context)
    {
        _iceI_playStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> playStreamAsync()
    {
        return _iceI_playStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> playStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_playStreamAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_playStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void pauseStream()
    {
        pauseStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void pauseStream(java.util.Map<String, String> context)
    {
        _iceI_pauseStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync()
    {
        return _iceI_pauseStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_pauseStreamAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_pauseStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pauseStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void stopStream()
    {
        stopStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stopStream(java.util.Map<String, String> context)
    {
        _iceI_stopStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync()
    {
        return _iceI_stopStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopStreamAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stopStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void playSong(int id)
    {
        playSong(id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void playSong(int id, java.util.Map<String, String> context)
    {
        _iceI_playSongAsync(id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> playSongAsync(int id)
    {
        return _iceI_playSongAsync(id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> playSongAsync(int id, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(id, context, false);
    }

    /**
     * @hidden
     * @param iceP_id -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_playSongAsync(int iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VLCPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VLCPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VLCPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VLCPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static VLCPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static VLCPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, VLCPrx.class, _VLCPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default VLCPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (VLCPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default VLCPrx ice_adapterId(String newAdapterId)
    {
        return (VLCPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default VLCPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (VLCPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default VLCPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (VLCPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default VLCPrx ice_invocationTimeout(int newTimeout)
    {
        return (VLCPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default VLCPrx ice_connectionCached(boolean newCache)
    {
        return (VLCPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default VLCPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (VLCPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VLCPrx ice_secure(boolean b)
    {
        return (VLCPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default VLCPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (VLCPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VLCPrx ice_preferSecure(boolean b)
    {
        return (VLCPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default VLCPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (VLCPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default VLCPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (VLCPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default VLCPrx ice_collocationOptimized(boolean b)
    {
        return (VLCPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default VLCPrx ice_twoway()
    {
        return (VLCPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default VLCPrx ice_oneway()
    {
        return (VLCPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default VLCPrx ice_batchOneway()
    {
        return (VLCPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default VLCPrx ice_datagram()
    {
        return (VLCPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default VLCPrx ice_batchDatagram()
    {
        return (VLCPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default VLCPrx ice_compress(boolean co)
    {
        return (VLCPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default VLCPrx ice_timeout(int t)
    {
        return (VLCPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default VLCPrx ice_connectionId(String connectionId)
    {
        return (VLCPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default VLCPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (VLCPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::VLC";
    }
}
